### ISSUE TITLE
deps - apt-get - `dpkg -l` doesn't always work

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise#433]
on the current Android/Linux stack the following fails:

```
steps:
- script
    deps:
      apt_get:
      - name: cmake
    inputs:
    - content: |
        set -ex
        which cmake
```

because `bitrise` CLI thinks `cmake` is installed, although it's not (fully?) installed. This is due to how the current apt-get deps check works, which uses `dpkg -l PACKAGENAME`.

In case of cmake the output of `dpkg -l cmake` right now is:

```
+ dpkg -l cmake
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  cmake          <none>       <none>       (no description available)
```

with an **exit code 0**, which makes `bitrise` CLI to interpret it as `cmake` is installed, while if you call a `which cmake` it shows that it actually isn't.
