### ISSUE TITLE
Failed to create inventory, error: Invalid inventory format: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise#603]
bitrise.yml :

```
format_version: "5"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
workflows:
  primary:
    steps:
    - script@1.1.5:
        title: Do anything with Script step

```

`.bitrise.secrets.yml`:

```
envs:
- ENV_ONE: 'this â  special char'
```

attaching `.bitrise.secrets.yml` and bitrise.yml as a ZIP as well, to be sure the right character is included. Note: removed the leading dot to make it a non hidden file - just change the filename back to start with `.` or specify `bitrise.secrets.yml` as the `--inventory=./bitrise.secrets.yml`.

[bitrise-configs.zip](https://github.com/bitrise-io/bitrise/files/2008960/bitrise-configs.zip)

With these configs if you try to `bitrise run primary` you'll get the following error:

```
$ bitrise run --inventory=./bitrise.secrets.yml primary

  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝

  version: 1.16.0

FATA[13:54:47] Failed to create inventory, error: Invalid invetory format: yaml: control characters are not allowed
```

that's all, CLI quits.
