### ISSUE TITLE
bitrise share start failing

### ISSUE THREAD

**Issue by realappie** [bitrise-io/bitrise#733]
I am running the `bitrise share start -c` command with a fork of https://github.com/bitrise-io/bitrise-steplib as input and I keep getting the following error

"FATA[19:52:45] Failed to save step spec, error: Failed to walk through path, error: not supported key found in options: is_sensitive "

A lot of steps in the official repository use the `is_sensitive` option, but I am not sure what I should do about it. I just want to publish my step 😅 

I am using bitrise cli version `1.42.0` 

My fork can be found at https://github.com/realappie/bitrise-steplib

**Comment by mjones-droid** [comment]
I suspect this is an issue with the step.yml file. Can you provide a link to the actual repo the step is in?

**Comment by realappie** [comment]
Here you go.

```
title: |-
  discord notifier
summary: |
   Notify discord channel about build status
description: |
   Notify discord channel about build status
website: https://github.com/realappie/bitrise-step-discord-notifier
source_code_url: https://github.com/realappie/bitrise-step-discord-notifier
support_url: https://github.com/realappie/bitrise-step-discord-notifier/issues
host_os_tags:
  - osx-10.10
  - ubuntu-16.04

type_tags:
  - notification

is_requires_admin_user: true
is_always_run: true
is_skippable: false
run_if: ""

deps:
  brew:
  - name: git
  - name: wget
  apt_get:
  - name: git
  - name: wget


toolkit:
  bash:
    entry_file: step.sh


inputs:
  - DISCORD_WEBHOOK_TOKEN: $DISCORD_WEBHOOK_TOKEN
    opts:
      description: |
        The discord webhook token, once you create a webhook in your server settings this will be the last
        segment of the url.
        You can also set it as a Secret with the name `DISCORD_WEBHOOK_TOKEN`
      is_required: true
      title: Discord webhook token id
  - DISCORD_WEBHOOK_ID: $DISCORD_WEBHOOK_ID
    opts:
      description: |
        The discord webhook id, once you create a webhook in your server settings this will be the second to last
        segment of the url and will usually be a big number. It will become before the DISCORD_WEBHOOK_TOKEN value
        You can also set it as a Secret with the name `DISCORD_WEBHOOK_ID`
      is_required: true
      title: Discord webhook id
```
