### ISSUE TITLE
Meta object breaks the workflow editor

### ISSUE THREAD

**Issue by dmarin** [bitrise-io/bitrise#780]
An exception is thrown when trying to use the workflow editor on a bitrise.yml that contains the meta object to specify the machine.

Error:
Exception: RespondWith: Error: json: unsupported type: map[interface {}]interface {}

Example of the meta used:

```
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: elite
```
